# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUHNrMZfr3aUxyKhtx3GtoWTEX1YC0g-
"""

# 1. Load & Understand the Data
import requests

url = "https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json"
responses = requests.get(url)
data = responses.json()

techniques =[]

for obj in data["objects"]:
    if obj.get("type") == "attack-pattern":
        techniques.append(obj)

for t in techniques:
  print(t)

# 2. Name-Based Intelligence

def threat_score(tech):
  scored_techniques = []
  for t in tech:
    # A. base Score
    score = 5

    # B.Name Based Intelligence
    if "credential" in t["name"]:
      score +=3
    if "execution" in t["name"]:
      score +=2
    if "privilege" in t["name"]:
      score +=3
    if "persistence" in t["name"]:
      score +=2
    if "lateral" in t["name"]:
      score +=2

    # C.  Description  Based Intelligence
    if "administrator" in t["description"]:
      score +=2
    if "remote" in t["description"]:
      score +=2
    if "bypass" in t["description"]:
      score +=2
    if "stealth" in t["description"]:
      score +=1

    scored_techniques.append((t["name"],score))
  return scored_techniques

# 3. Score All Techniques
scored_techniques = threat_score(techniques)
# print(type(scored_techniques))

for st in scored_techniques:
  print("Technique Name: ",st[0])
  print("Score: ",st[1])
  print()

# 4. Prioritize Threat
# sorting using slection sort
for i in range(len(scored_techniques)):
    for j in range(i + 1, len(scored_techniques)):
        if scored_techniques[i][1] < scored_techniques[j][1]:
            scored_techniques[i], scored_techniques[j] = scored_techniques[j], scored_techniques[i]

print("Top 10 highest risk techniques are: ")
print()
for st in scored_techniques[:10]:
  print("Technique Name: ",st[0])
  print("Score: ",st[1])
  print()

print("Critical Threats with score>=8.9 are: ")
print()
for st in scored_techniques:
  if st[1]>=8.9:
    print("Technique Name: ",st[0])
    print("Score: ",st[1])
    print()