# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBfVpCpTHJnX3iNHjrWyL_0noXcYYX_v
"""

# Part A: Nmap Scanning
!sudo apt-get update
!sudo apt-get install nmap
!pip install python-nmap

# Part A: Nmap Scanning
import nmap

nm = nmap.PortScanner()
target = "scanme.nmap.org"

# Part A: Nmap Scanning
# baisc scan no arguments
nm.scan(target)
print("Basic Scan Results")

for host in nm.all_hosts():
    print("Host:", host)
    print("Protocols:",proto)
    for proto in nm[host].all_protocols():
        for port in nm[host][proto]:
            print("Port", port, "is open")

# Part A: Nmap Scanning
# with arugment -sV used for geeting service and version
nm.scan(target, arguments="-sV")
print("With argument: -sV (Service and version)\n")

for host in nm.all_hosts():
    for proto in nm[host].all_protocols():
        for port in nm[host][proto]:
            service = nm[host][proto][port]["name"]
            product = nm[host][proto][port].get("product")
            version = nm[host][proto][port].get("version")
            print("Port", port, "\tService:", service, "\tProduct:", product, "\tVersion:", version)

# Part A: Nmap Scanning
# with arugment -O used for detecting OS
nm.scan(target, arguments="-O")
print("\nWith argument: -O (OS)\n")

for host in nm.all_hosts():
    print("Host:", host)
    print("Protocols:",proto)
    if "osmatch" in nm[host]:
        for os in nm[host]["osmatch"]:
            print("Possible OS:", os["name"])
    else:
        print("No OS information detected")

# Part A: Nmap Scanning
# with arugment -A used for Advanced Scan
nm.scan(target, arguments="-A")
print("\nWith argument: -A (Advanced Scan)\n")

for host in nm.all_hosts():
    print("Host:", host)
    print("Protocols:",proto)
    if "osmatch" in nm[host]:
        print("OS detection data available")

# Part B: VirusTotal Intelligence Gathering
import requests
from google.colab import userdata
API_KEY = userdata.get('API_KEY')

url = "https://www.virustotal.com/api/v3/domains/" + target
headers = {
    "x-apikey": API_KEY
}
response = requests.get(url, headers=headers)
data = response.json()

# Part B: VirusTotal Intelligence Gathering
print("Reputation Results")
stats = data["data"]["attributes"]["last_analysis_stats"]
# print(stats.keys())

print("Harmless:", stats["harmless"])
print("Malicious:", stats["malicious"])
print("Suspicious:", stats["suspicious"])
print("Undetected:", stats["undetected"])

# Part B: VirusTotal Intelligence Gathering
print("Domain and IP Intelligence")

attributes = data["data"]["attributes"]
print(attributes.keys())
print("\nRegistrar:", attributes.get("registrar"))
print("Popularity Ranks:", attributes.get("popularity_ranks"))
print("Reputation:", attributes.get("reputation"))
print("creation Date:", attributes.get("creation_date"))
print("Last Update:", attributes.get("last_update_date"))
print("Last Analysis Results:", attributes.get("last_analysis_results"))

# Part B: VirusTotal Intelligence Gathering
print("Historical and Contextual Data")

if "categories" in attributes:
    print("Domain Categories:")
    for key in attributes["categories"]:
        print("-", attributes["categories"][key])
else:
    print("No category data available")

# Part B: VirusTotal Intelligence Gathering
print("Security Observations")
if stats["malicious"] == 0:
    print(target,"- is Safe")
else:
    print(target,"- is Malicious")